### PR TITLE
Flake8 Cleanup and Praying I didn't break anything

### PR DESCRIPTION
**Pull request by hpincket**
Lots and lots of changes.

### CODE REVIEW

**Comment by hpincket** [comment]
All the above says is that our code is Flake8 compliant.

**Comment by joengelm** [comment]
@hpincket Sorry, I merged that too soon (and have now reverted it). I think this will introduce Python errors because of the way the imports have been rearranged. Can you try running this locally, fix any errors (or confirm that there are none), and put up a new PR?

**Comment by joengelm** [comment]
For reference, this is the error that occurred on our server after merging your changes and rebuilding:
```
Sep 02 18:53:02 brown-apis app/web.1:  Traceback (most recent call last):
Sep 02 18:53:02 brown-apis app/web.1:    File "/app/.heroku/python/lib/python3.4/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker 
Sep 02 18:53:02 brown-apis app/web.1:      worker.init_process() 
Sep 02 18:53:02 brown-apis app/web.1:    File "/app/.heroku/python/lib/python3.4/site-packages/gunicorn/workers/base.py", line 118, in init_process 
Sep 02 18:53:02 brown-apis app/web.1:      self.wsgi = self.app.wsgi() 
Sep 02 18:53:02 brown-apis app/web.1:    File "/app/.heroku/python/lib/python3.4/site-packages/gunicorn/app/base.py", line 67, in wsgi 
Sep 02 18:53:02 brown-apis app/web.1:      self.callable = self.load() 
Sep 02 18:53:02 brown-apis app/web.1:    File "/app/.heroku/python/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 65, in load 
Sep 02 18:53:02 brown-apis app/web.1:      return self.load_wsgiapp() 
Sep 02 18:53:02 brown-apis app/web.1:    File "/app/.heroku/python/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp 
Sep 02 18:53:02 brown-apis app/web.1:      return util.import_app(self.app_uri) 
Sep 02 18:53:02 brown-apis app/web.1:    File "/app/.heroku/python/lib/python3.4/site-packages/gunicorn/util.py", line 355, in import_app 
Sep 02 18:53:02 brown-apis app/web.1:      __import__(module) 
Sep 02 18:53:02 brown-apis app/web.1:    File "/app/api/__init__.py", line 7, in <module> 
Sep 02 18:53:02 brown-apis app/web.1:      import api.meta 
Sep 02 18:53:02 brown-apis app/web.1:    File "/app/api/meta.py", line 4, in <module> 
Sep 02 18:53:02 brown-apis app/web.1:      from api import app, db, requires_auth, make_json_error 
Sep 02 18:53:02 brown-apis app/web.1:  ImportError: cannot import name 'app' 
```

**Comment by hpincket** [comment]
I remember this case in the code. Ill fix it tomorrow. 

And yes,  I was putting off figuring out how to set it all up. Will do that too. 

On September 2, 2016 7:03:40 PM PDT, Joe Engelman <notifications@github.com> wrote:
>For reference, this is the error that occurred on our server after
>merging your changes and rebuilding:
>```
>Sep 02 18:53:02 brown-apis app/web.1:  Traceback (most recent call
>last):
>Sep 02 18:53:02 brown-apis app/web.1:    File
>"/app/.heroku/python/lib/python3.4/site-packages/gunicorn/arbiter.py",
>line 507, in spawn_worker 
>Sep 02 18:53:02 brown-apis app/web.1:      worker.init_process() 
>Sep 02 18:53:02 brown-apis app/web.1:    File
>"/app/.heroku/python/lib/python3.4/site-packages/gunicorn/workers/base.py",
>line 118, in init_process 
>Sep 02 18:53:02 brown-apis app/web.1:      self.wsgi = self.app.wsgi() 
>Sep 02 18:53:02 brown-apis app/web.1:    File
>"/app/.heroku/python/lib/python3.4/site-packages/gunicorn/app/base.py",
>line 67, in wsgi 
>Sep 02 18:53:02 brown-apis app/web.1:      self.callable = self.load() 
>Sep 02 18:53:02 brown-apis app/web.1:    File
>"/app/.heroku/python/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py",
>line 65, in load 
>Sep 02 18:53:02 brown-apis app/web.1:      return self.load_wsgiapp() 
>Sep 02 18:53:02 brown-apis app/web.1:    File
>"/app/.heroku/python/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py",
>line 52, in load_wsgiapp 
>Sep 02 18:53:02 brown-apis app/web.1:      return
>util.import_app(self.app_uri) 
>Sep 02 18:53:02 brown-apis app/web.1:    File
>"/app/.heroku/python/lib/python3.4/site-packages/gunicorn/util.py",
>line 355, in import_app 
>Sep 02 18:53:02 brown-apis app/web.1:      __import__(module) 
>Sep 02 18:53:02 brown-apis app/web.1:    File "/app/api/__init__.py",
>line 7, in <module> 
>Sep 02 18:53:02 brown-apis app/web.1:      import api.meta 
>Sep 02 18:53:02 brown-apis app/web.1:    File "/app/api/meta.py", line
>4, in <module> 
>Sep 02 18:53:02 brown-apis app/web.1:      from api import app, db,
>requires_auth, make_json_error 
>Sep 02 18:53:02 brown-apis app/web.1:  ImportError: cannot import name
>'app' 
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/hackatbrown/apis/pull/62#issuecomment-244520583

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hpincket** [comment]
I have a possible fix for this. It starts up, but I'm not sure if it will break farther down some code path.

**Comment by joengelm** [comment]
Can you put up the fix in a new PR?

**Pull request merged**
